name: CI Build

on:
  push:
    branches: [ master, hive3 ]
  pull_request:
    branches: [ master, hive3 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 9, 10, 11]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: ./gradlew :serde:check
